 export const sidebarlinks =[
    {
        label:'Home',
        route:'/',
        imgUrl:'/icons/home.svg'
    },
    {
        label:'Upcomming',
        route:'/upcoming',
        imgUrl:'/icons/upcoming.svg'
    },
    {
        label:'History',
        route:'/history',
        imgUrl:'/icons/previous.svg'
    },
    {
        label:'Recordings',
        route:'/recordings',
        imgUrl:'/icons/recordings.svg'
    },
    {
        label:'Colab',
        route:'/colab',
        imgUrl:'/icons/add-personal.svg'
    },
]
export const avatarImages = [
    '/images/avatar-1.jpeg',
    '/images/avatar-2.jpeg',
    '/images/avatar-3.png',
    '/images/avatar-4.png',
    '/images/avatar-5.png',
  ];